name: json_serializable_type_helper_utils
description: Helper package for adding TypeHelpers to json_serializable. Can be used to add support for container types like collections.
version: 1.0.1
homepage: https://github.com/knaeckeKami/json_serializable_immutable_collections/tree/master/json_serializable_type_helper_utils

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  analyzer: '>=0.39.0 <0.41.0'
  json_serializable: '>=3.3.0 <4.0.0'

dev_dependencies:

