name: json_serializable_mobx
description: Adding support for mobx collections for json_serializable
version: 0.4.0
homepage: https://github.com/knaeckeKami/immutable_json_list_serializer

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dev_dependencies:
  test: ^1.15.4

dependencies:
  json_serializable:  ">=4.0.0-nullsafety.0 <5.0.0"
  json_annotation:  ">=4.0.0-nullsafety.0 <5.0.0"
  json_serializable_type_helper_utils: ^2.0.0-nullsafety.0
  mobx: "^2.0.0-nullsafety.2"
  build_runner: ^1.11.0
  source_gen: ">=0.9.4 <=1.0.0"
  analyzer: ">=0.40.0 <0.42.0"
  build: ^1.6.1
