name: immutable_json_list_builder
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:


dev_dependencies:
  json_serializable: <4.0.0
  built_collection: <5.0.0
  build_runner: ^1.7.4
  test: 1.12.0
