name: json_serializable_immutable_collections
description: Adding support for immutable collections for json_serializable
version: 0.0.1
author:
homepage: https://github.com/knaeckeKami/immutable_json_list_serializer

environment:
  sdk: ">=2.7.0 <3.0.0"


dev_dependencies:
  json_serializable: <4.0.0
  built_collection: <5.0.0
  build_runner: ^1.7.4
  test: 1.12.0
  kt_dart: <=1.0.0
