name: json_serializable_immutable_collections
description: Adding support for immutable collections for json_serializable
version: 0.4.2
homepage: https://github.com/knaeckeKami/immutable_json_list_serializer

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.15.4

dependencies:
  json_serializable: ">=3.4.0 <4.0.0"
  json_annotation: ^3.0.1
  json_serializable_type_helper_utils: ^1.0.1
  built_collection: ">=4.0.0 <5.0.0"
  build_runner: ^1.8.0
  kt_dart: ">=0.6.0 <=1.0.0"
  source_gen: ">=0.9.4 <=1.0.0"
  analyzer: '^0.39.0'
  build: ^1.3.0
