name: json_serializable_immutable_collections
description: Adding support for immutable collections for json_serializable
version: 0.6.0
homepage: https://github.com/knaeckeKami/immutable_json_list_serializer

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8

dependencies:
  json_serializable:  ">=4.1.0 <5.0.0"
  json_annotation:  ">=4.0.0 <5.0.0"
  built_collection: "^5.0.0"
  build_runner: ^1.11.0
  source_gen: "^1.0.0"
  analyzer: "^1.0.0"
  build: ^2.0.0
  json_serializable_kt_typehelpers:
    path: ../json_serializable_kt_typehelpers
  json_serializable_built_typehelpers:
    path: ../json_serializable_built_typehelpers
