name: json_serializable_mobx
description: Adding support for mobx collections for json_serializable
version: 0.6.0
homepage: https://github.com/knaeckeKami/immutable_json_list_serializer

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
  mobx: ^2.0.0-nullsafety.5

dependencies:
  json_serializable:  ^4.1.0
  build_runner: ^1.11.0
  analyzer: ^1.0.0
  source_gen: ^1.0.0
  build: ^2.0.0
  json_serializable_mobx_typehelpers: ^1.0.0
  json_annotation: ^4.0.1