name: json_serializable_fic_typehelpers
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  source_gen: ^1.0.0
  fast_immutable_collections: ^2.0.2
  json_serializable: ^4.1.0
  json_serializable_type_helper_utils:
    path: ../json_serializable_type_helper_utils

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
