targets:
  $default:
    builders:
      # exclude the builder for fast_immutable_collections to avoid builder conflicts
      json_serializable_fic:
        generate_for:
           include:
           exclude:
            - test/**
            - lib/**
            - example/**
      # exclude the default json_serializable builder
      json_serializable:json_serializable:
        generate_for:
          include:
          exclude:
            - test/**
            - lib/**
            - example/**
      # exclude the mobx builder 
      json_serializable_mobx:
        generate_for:
          include:
          exclude:
           - test/**
           - lib/**
           - example/**
      # exclude the built_collection/kt_dart builder 
      json_serializable_immutable_collections:
        generate_for:
          include:
          exclude:
            - test/**
            - lib/**
            - example/**
      # add our custom builder that builds everything (see builder.dart and the builders section below)
      # your will need to change the name <project_package:combine_example>
      combine_example:everything_builder:
        options:
          explicit_to_json: true
        generate_for:
         include:
            - lib/**
            - test/**
            - example/**


builders:
  # you can rename this but be sure the referene it correctly in the target section above
  everything_builder:
    # change to the path of your builder.dart file
    import: "package:combine_example/builder.dart"
    # leave this as is
    builder_factories: ["jsonSerializable"]
    build_extensions: {".dart": ["json_serializable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
